# Generated by Django 5.1.4 on 2024-12-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('organizer_post', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('Organizer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='home.organization')),
            ],
        ),
    ]
