# Generated by Django 5.1.4 on 2024-12-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_organization_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='duration',
        ),
    ]
