# Generated by Django 5.1.4 on 2024-12-14 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='membersprofile/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MembersManifestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.FileField(upload_to='manifestos/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_manifesto', to='home.members')),
            ],
        ),
    ]
