# Generated by Django 5.1.4 on 2024-12-14 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_members_photo_membersmanifestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='photo',
        ),
        migrations.AddField(
            model_name='membersmanifestos',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profilemem/'),
            preserve_default=False,
        ),
    ]
