# Generated by Django 5.1.4 on 2024-12-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_members_photo_membersmanifestos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_vote', to='home.members')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_organization', to='home.organization')),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to='home.members')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
