# Generated by Django 5.1.4 on 2024-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_membersvote_voted_voterlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersvote',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='home.voterlist'),
        ),
    ]
