# Generated by Django 5.1.4 on 2024-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_membersvote_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
